name: Build Peregrine with Vlang
on: 
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "./github/**"
  push:
    branches:
      - "main"
  

jobs:
  build-peregrine:
    name: Build Peregrine
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up V version latest
      uses: nocturlab/setup-vlang-action@v1
      with:
        v-version: latest
      id: v
    - name: Build Peregrine
      run: |
        v ./Peregrine/peregrine.v -o peregrine -path='builtin/'
        ls
    - uses: actions/upload-artifact@v2
      with:
        name: peregrine-bin
        path: peregrine
        retention-days: 1
  run-tests:
    needs: build-peregrine
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install build-essential
        run: sudo apt-get install build-essential
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Artifact Compiled peregrine
        uses: actions/download-artifact@v2
        with:
          name: peregrine-bin
          path: ./Peregrine/
      - name: Run tests
        run: | 
          cd Peregrine
          ls
          pwd
          sudo chmod 777 ./peregrine
          sudo bash ./run_tests_ci.sh
          echo TEST DONE